services:
    ollama-admin-ui:
      build: .
      ports:
        - 8001:8001
      environment:
        OLLAMA_ADDRESS: "http://ollama:11434"
    ollama:
        volumes:
            - ollama:/root/.ollama
        ports:
            - 11434:11434
        container_name: ollama
        image: ollama/ollama
volumes:
    ollama:
        name: ollama
